FROM codelabs-base:latest As development

WORKDIR /usr/src/app

COPY . .

RUN npm build

FROM codelabs-prod as prod

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/dist ./dist

CMD ["node", "dist/main"]